### PR TITLE
Hindi Translation added

### PR DESCRIPTION
**Pull request by Yugal41735**
## Summary

Added Hindi Translation

image

Ref => #48 

## Type of change

- [ ] Bug fix (added a non-breaking change which fixes an issue)
- [x] New feature (added a non-breaking change which adds functionality)
- [ ] Updated documentation (updated the readme, templates, or other repo files)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?

- [x] Added or updated test cases to test new features

### CODE REVIEW

**Comment by DenverCoder1** [comment]
Hi, sorry I didn't get to merge this one.

#60 was opened about an hour and a half before yours so I ended up merging that one.

* #60 

I did notice, however, that your translation for "months" and "years" appears to be slightly different.

Let me know if you think the translations in your PR should override the ones in #60, otherwise I'll close this. Hopefully, we will see some contributions from you merged in the future.

**Comment by Yugal41735** [comment]
months one could be edited.

**Comment by Yugal41735** [comment]
If you want I can do those changes.

**Comment by DenverCoder1** [comment]
I suppose you could look at youtube.com with language set to Hindi and see what they do for translating these. If you can make it accurate to the YouTube site (if it's not already), that would be good.

Also note, the filename should be `hi.yml` for Hindi and the first line should be `hi:`.

If you merge main, which it seems you did, you should see the file.

**Comment by DenverCoder1** [comment]
Looks like YouTube uses `माह पहले` for months and `वर्ष पहले` for years which is what we currently have, so I suppose there's no need to update it. I believe this is what #60 already has.

image

Let me know if you find anything different, but I will close for now. :+1:

**Pull request closed without merging**
